sheknowsnetwork/urls.py
from django.contrib import admin
from django.urls import include, path
from skn_professionals.views import index, profile, find_professionals, detail_of_professional, recommend_professional, requester_profile
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('', index, name='index'),
	path('profile', profile, name='profile'),
    path('requester-profile', requester_profile, name='requester_profile'),
	path('find-professionals', find_professionals, name='find_professionals'),
    path('recommend-professional', recommend_professional, name='recommend_professional'),
    path('p/<int:id_of_professional>/', detail_of_professional, name='detail_of_professional'),
	path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skn_professionals/urls.py
from django.urls import path

from . import views


app_name = 'Professionals'

urlpatterns = [
    
]

skn_professionals/models.py
# Create your models here.

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import RegexValidator
from django_countries.fields import CountryField
from multiselectfield import MultiSelectField


class User(AbstractUser):

    USER_TYPE = (
        ('Professional', 'Professional'),
        ('Partner', 'Partner'),
        ('Requesting Agency', 'Requesting Agency'),
    )
    user_type = models.CharField(max_length=20, choices=USER_TYPE, default="Professional")



class ProfessionalProfile(models.Model):

	FIELD_OF_EXPERTISE = (
        ('Agriculture', 'Agriculture'),
        ('Business/Commerce & Industry', 'Business/Commerce & Industry'),
        ('Communications, Media, IT', 'Communications, Media, IT'),
        ('Criminology & Criminal Justice', 'Criminology & Criminal Justice'),
        ('Culture & Heritage', 'Culture & Heritage'),
        ('Development and International Development', 'Development and International Development'),
        ('Diplomacy and International Relations', 'Diplomacy and International Relations'),
        ('Economy', 'Economy'),
        ('Education', 'Education'),
        ('Elections', 'Elections'),
        ('Energy', 'Energy'),
        ('Employment', 'Employment'),
        ('Finance, Banking, Microfinance', 'Finance, Banking, Microfinance'),
        ('Fiscal Policy', 'Fiscal Policy'),
        ('Government & Politics', 'Government & Politics'),
        ('Health', 'Health'),
        ('History of Ghana', 'History of Ghana'),
        ('Humanities', 'Humanities'),
        ('Infrastructure & Planning', 'Infrastructure & Planning'),
        ('Law/Legal', 'Law/Legal'),
        ('Linguistics/Language', 'Linguistics/Language'),
        ('Public Service & Public Administration', 'Public Service & Public Administration'),
        ('Security & Defense', 'Security & Defense'),
        ('Social Sciences', 'Social Sciences'),
        ('Science & STEM', 'Science & STEM'),
        ('Social Justice, Gender, Youth & Diversity', 'Social Justice, Gender, Youth & Diversity'),
        ('Sports', 'Sports'),
        ('Violence Against Women', 'Violence Against Women'),
        ('Women and Politics', 'Women and Politics'),
        ('Women in Media', 'Women in Media'),
        ('Other', 'Other'),
    )

	LEVEL_OF_EXPERTISE = (
		('Early Career: 3-6 Years', 'Early Career: 3-6 Years'),
		('Mid Career: 7-12 Years', 'Mid Career: 7-12 Years'),
		('Experienced: 12+ Years', 'Experienced: 12+ Years'),
	)

	DISCOVER_SKN = (
		('Friends & Family', 'Friends & Family'),
		('Social Media', 'Social Media'),
		('Publications', 'Publications'),
		('TV', 'TV'),
		('Radio', 'Radio'),
		('Other', 'Other'),
	)

	CERTIFY_ACCOUNT = (
		('Yes', 'Yes'),
		('No', 'No'),
	)

	APPROVED = (
		('Yes', 'Yes'),
		('No', 'No'),
	)

	AVAILABLE_FOR_INTERESTS = (
		('Media Engagements', 'Media Engagements'),
		('Conference Speaking', 'Conference Speaking'),
		('Board', 'Board'),
		('Consultancy', 'Consultancy'),
	)

	WANT_FOR_SERVICES = (
		('Compensation', 'Compensation'),
		('Compensation When Offered', 'Compensation When Offered'),
		('Experience Is My Focus', 'Experience Is My Focus'),
	)

	phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")

	
	first_name = models.CharField(max_length=45)
	last_name = models.CharField(max_length=45)
	phone_number = models.CharField(validators=[phone_regex], max_length=15)
	country_of_residence = CountryField(blank_label='(Select Country)')
	nationality = CountryField(blank_label='(Select Country)', blank=True, null=True)
	region_of_residence = models.CharField(max_length=150)
	town_or_city_of_residence = models.CharField(max_length=150)
	field_of_expertise = models.CharField(max_length=60, choices=FIELD_OF_EXPERTISE)
	other_field_of_expertise_name = models.CharField(max_length=150, blank=True)
	specialties_under_expertise = models.CharField(max_length=150)
	level_of_expertise = models.CharField(max_length=30, choices=LEVEL_OF_EXPERTISE)
	job_title = models.CharField(max_length=60)
	job_description = models.CharField(max_length=300)
	institution = models.CharField(max_length=150)
	link_to_social_media_handle = models.CharField(max_length=150, blank=True, null=True)
	languages_spoken = models.CharField(max_length=100)
	profile = models.CharField(max_length=300)
	certify_account = models.CharField(max_length=10, choices=CERTIFY_ACCOUNT)
	cv_resume = models.FileField()
	want_for_services = models.CharField(max_length=30, choices=WANT_FOR_SERVICES)
	available_for_interests = MultiSelectField(choices=AVAILABLE_FOR_INTERESTS)
	assistant_name = models.CharField(max_length=45, blank=True, null=True)
	assistant_phone_number = models.CharField(validators=[phone_regex], max_length=15, blank=True, null=True)
	assistant_email = models.EmailField(max_length=250, blank=True, null=True)
	referee_one_full_name = models.CharField(max_length=60)
	referee_one_phone_number = models.CharField(validators=[phone_regex], max_length=15)
	referee_one_email = models.EmailField(max_length=150)
	referee_one_workplace = models.CharField(max_length=60)
	referee_two_full_name = models.CharField(max_length=60, blank=True, null=True)
	referee_two_phone_number = models.CharField(validators=[phone_regex], max_length=15, blank=True, null=True)
	referee_two_email = models.EmailField(max_length=150, blank=True, null=True)
	referee_two_workplace = models.CharField(max_length=60, blank=True, null=True)
	how_did_you_discover_skn = models.CharField(max_length=20, choices=DISCOVER_SKN, default="Other")
	photo = models.ImageField(blank=True, null=True)
	terms_and_conditions_confirmed = models.BooleanField()
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	admin_approved = models.CharField(max_length=5, choices=APPROVED, default="No")
	created_on = models.DateTimeField(auto_now_add=True)
    

	def __unicode__(self):
		return self.first_name


class RequesterProfile(models.Model):

	APPROVED = (
		('Yes', 'Yes'),
		('No', 'No'),
	)

	phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")

	requester_full_name = models.CharField(max_length=150)
	requester_organization = models.CharField(max_length=60)
	requester_phone_number = models.CharField(validators=[phone_regex], max_length=15)
	requester_website = models.CharField(max_length=60)
	requester_photo_id = models.ImageField(blank=True, null=True)
	referee_one_full_name = models.CharField(max_length=60, blank=True, null=True)
	referee_one_phone_number = models.CharField(validators=[phone_regex], max_length=15, blank=True, null=True)
	referee_one_email = models.EmailField(max_length=150, blank=True, null=True)
	referee_one_social_media_handle = models.CharField(max_length=150, blank=True, null=True)
	referee_one_workplace = models.CharField(max_length=60, blank=True, null=True)
	referee_two_full_name = models.CharField(max_length=60, blank=True, null=True)
	referee_two_phone_number = models.CharField(validators=[phone_regex], max_length=15, blank=True, null=True)
	referee_two_email = models.EmailField(max_length=150, blank=True, null=True)
	referee_two_social_media_handle = models.CharField(max_length=150, blank=True, null=True)
	referee_two_workplace = models.CharField(max_length=60, blank=True, null=True)
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	admin_approved = models.CharField(max_length=5, choices=APPROVED, default="No")
	created_on = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.requester_full_name



class RecommendProfessional(models.Model):

	TITLE = (
		('Professor', 'Professor'),
		('Dr', 'Dr'),
		('Mr', 'Mr'),
		('Ms', 'Ms'),
		('Other', 'Other'),
	)

	INFORM_PROFESSIONAL = (
		('Yes', 'Yes'),
		('No', 'No'),
	)

	phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")

	
	title_of_recommender = models.CharField(max_length=10, choices=TITLE)
	recommender_first_name = models.CharField(max_length=45)
	recommender_last_name = models.CharField(max_length=45)
	recommender_email = models.EmailField(max_length=150)
	recommender_phone_number = models.CharField(validators=[phone_regex], max_length=15)
	let_professional_know = models.CharField(max_length=10, choices=INFORM_PROFESSIONAL)

	title_of_professional = models.CharField(max_length=10, choices=TITLE)
	professional_full_name = models.CharField(max_length=150)
	professional_phone_number = models.CharField(validators=[phone_regex], max_length=15)
	professional_email = models.EmailField(max_length=150)
	professional_expertise = models.TextField()
	created_on = models.DateTimeField(auto_now_add=True)

    

	def __unicode__(self):
		return self.professional_full_name

skn_professionals/forms.py
from django import forms
from skn_professionals.models import ProfessionalProfile, RequesterProfile, RecommendProfessional


class ProfessionalProfileForm(forms.ModelForm):
    class Meta:
        model = ProfessionalProfile
        exclude = ['user', 'nationality', 'created_on', 'admin_approved']



class RequesterProfileForm(forms.ModelForm):
    class Meta:
        model = RequesterProfile
        exclude = ['user', 'created_on', 'admin_approved']

    def clean(self):
        cleaned_data = super().clean()
        requester_photo_id = cleaned_data.get("requester_photo_id")
        referee_one_email = cleaned_data.get("referee_one_email")

        if not requester_photo_id and not referee_one_email:
        	raise forms.ValidationError("You need to provide a photo id or referees.")



class RecommendProfessionalForm(forms.ModelForm):
    class Meta:
        model = RecommendProfessional
        exclude = ['created_on']

skn_professionals/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django import forms
from skn_professionals.models import ProfessionalProfile, RequesterProfile
from skn_professionals.forms import ProfessionalProfileForm, RecommendProfessionalForm, RequesterProfileForm

# Create your views here.



def index(request):
	if request.method == 'GET':

		return redirect('/accounts/signup')



@login_required
def profile(request):
	if request.method == 'GET':

		user = request.user

		if user.user_type == "Professional":

			try:
				profile = ProfessionalProfile.objects.get(user=request.user)
			except ProfessionalProfile.DoesNotExist:
				profile = None

			if profile is None:
				form = ProfessionalProfileForm()
				return render(request, 'add_profile.html', {'form': form})
			else:
				return render(request, 'profile.html', {'user': request.user, 'profile': profile})

		elif user.user_type == "Requesting Agency":
			return redirect('/find-professionals')

		else:
			return redirect('/find-professionals')
	elif request.method == 'POST':
		form = ProfessionalProfileForm(request.POST, request.FILES)
		if form.is_valid():
			pro_profile = form.save(commit=False)
			pro_profile.user = request.user
			pro_profile.save()
			return redirect('/profile')
		else:
			return render(request, 'add_profile.html', {'form': form})



@login_required
def find_professionals(request):
	if request.method == 'GET':

		if request.user.user_type == "Requesting Agency":

			try:
				profile = RequesterProfile.objects.get(user=request.user)
			except RequesterProfile.DoesNotExist:
				profile = None

			if profile is None:
				return redirect('/requester-profile')
			elif profile.admin_approved == "Yes":
				pass
			elif profile.admin_approved == "No":
				return render(request, 'not_allowed.html')


		try:
			professionals = ProfessionalProfile.objects.filter().order_by('-created_on')
		except ProfessionalProfile.DoesNotExist:
			professionals = None


		return render(request, 'find.html', {'professionals': professionals})



@login_required
def detail_of_professional(request, id_of_professional):
	if request.method == "GET":

		try:
			professional = ProfessionalProfile.objects.get(pk=id_of_professional)
		except ProfessionalProfile.DoesNotExist:
			professional = None

		return render(request, 'profile_detail.html', {'profile': professional})



@login_required
def requester_profile(request):
	if request.method == "POST":
		form = RequesterProfileForm(request.POST, request.FILES)
		if form.is_valid():

			req_profile = form.save(commit=False)
			req_profile.user = request.user
			req_profile.save()
			return render(request, 'choose_request_service.html')

		else:
			return render(request, 'add_requester_profile.html', {'form': form})
	elif request.method == "GET":
		try:
			profile = RequesterProfile.objects.get(user=request.user)
		except RequesterProfile.DoesNotExist:
			profile = None

		if profile is None:
			form = RequesterProfileForm()
			return render(request, 'add_requester_profile.html', {'form': form})
		elif profile.admin_approved == "Yes":
			return redirect('/find-professionals')
		elif profile.admin_approved == "No":
			return render(request, 'choose_request_service.html')






def recommend_professional(request):
	if request.method == 'GET':
		form = RecommendProfessionalForm()
		return render(request, 'recommend.html', {'form': form})
	elif request.method == 'POST':
		form = RecommendProfessionalForm(request.POST)
		if form.is_valid():
			form.save()
			return render(request, 'recommend_thankyou.html')
		else:
			return render(request, 'recommend.html', {'form': form})

skn_professionals/templates/add_requester_profile.html
{% extends "account/base.html" %}
{% load static %}


{% block head_title %} Add Requester Profile - She Knows Network{% endblock %}


{% block content %}

<main class="content">

    <!-- <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
    </div> -->
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
        <div class="col-xl-9">
            <a href="/"><img class="mx-auto d-block" src="{% static 'img/skn_logo.png' %}"></a>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-xl-9">
            <div class="card card-body bg-white border-light shadow-sm mb-4">
                <br>
                <div class="text-center text-md-center mb-4 mt-md-0">
                    <h1 class="mb-0 h3">Register As A Requesting Agency</h1>
                </div>

                <div class="errors-ui">{{ form.non_field_errors }}</div>

                <div class="form-headers">
                    <h2 class="h5 mb-4">Step 1: Privacy Policy</h2>
                </div>

                <p class="mb-0">We take your privacy and information seriously as the SKN community thrives on transparency and trust. PLEASE NOTE that in compliance with Ghana’s Data Protection Act, 2012 the She Knows Network will only use data you have willing submitted and for the purposes submitted for. We do not share your information with any third parties except partners you have consented to by way of processing your data for opportunities. Members of the network and so are our partners are verified and accredited.</p><br>

                
                <div class="form-headers">
                    <h2 class="h5 mb-4">Step 2: Personal Details</h2>
                </div>
                
                <form method="POST" action="/requester-profile" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-8 mb-3">
                            <div>
                                <label for="id_requester_full_name">Full Name<span class="skn-required">*</span></label>
                                <div class="errors-ui">{{ form.requester_full_name.errors }}</div>
                                <input class="form-control" id="id_requester_full_name" name="requester_full_name" type="text" placeholder="Enter your full name" required>
                            </div>
                        </div>
                    </div>
                    <div class="row align-items-center">
                        <div class="col-md-6 mb-3">
                            <div class="form-group">
                                <label for="id_requester_phone_number">Phone Number<span class="skn-required">*</span></label>
                                 <div class="errors-ui">{{ form.requester_phone_number.errors }}</div>
                                <input class="form-control" id="id_requester_phone_number" name="requester_phone_number" type="tel" placeholder="+233245000000" required>
                            </div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <div class="form-group">
                                <label for="id_requester_organization">Institution/Organization<span class="skn-required">*</span></label>
                                 <div class="errors-ui">{{ form.requester_organization.errors }}</div>
                                <input class="form-control" id="id_requester_organization" name="requester_organization" type="text" placeholder="What organization do you belong to?">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <div class="form-group">
                                <label for="id_requester_website">Your website<span class="skn-required">*</span></label>
                                 <div class="errors-ui">{{ form.requester_website.errors }}</div>
                                <input class="form-control" id="id_requester_website" name="requester_website" type="text" placeholder="https://www.company.com">
                            </div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <div class="form-group">
                                <label for="id_requester_photo_id">Attach A Photo ID</label>
                                 <div class="errors-ui">{{ form.requester_photo_id.errors }}</div>
                                <div class="form-file mb-3">
                                    <input type="file" class="form-control" id="id_requester_photo_id" name="requester_photo_id">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-headers">
                        <h2 class="h5 mb-4">Step 3: Referees (This is optional if you provided a photo ID)</h2>
                    </div>
                    <div class="row">
                        <strong class="my-4"> Referee 1 </strong>
                        <div class="col-md-6 mb-3">
                            <div>
                                <label for="id_referee_one_full_name">Full name</label>
                                 <div class="errors-ui">{{ form.referee_one_full_name.errors }}</div>
                                <input class="form-control" id="id_referee_one_full_name" name="referee_one_full_name" type="text" placeholder="Full name">
                            </div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <div>
                                <label for="id_referee_one_email">Email</label>
                                 <div class="errors-ui">{{ form.referee_one_email.errors }}</div>
                                <input class="form-control" id="id_referee_one_email" name="referee_one_email" type="text" placeholder="example@gmail.com">
                            </div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <div>
                                <label for="id_referee_one_phone_number">Phone Number</label>
                                 <div class="errors-ui">{{ form.referee_one_phone_number.errors }}</div>
                                <input class="form-control" id="id_referee_one_phone_number" name="referee_one_phone_number" type="tel" placeholder="+233245000000">
                            </div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <div>
                                <label for="id_referee_one_workplace">Company</label>
                                 <div class="errors-ui">{{ form.referee_one_workplace.errors }}</div>
                                <input class="form-control" id="id_referee_one_workplace" name="referee_one_workplace" type="text" placeholder="Company Ltd.">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-8 mb-3">
                                <div class="form-group">
                                    <label for="id_referee_one_social_media_handle">Link To Social Media Handle</label>
                                     <div class="errors-ui">{{ form.referee_one_social_media_handle.errors }}</div>
                                    <input class="form-control" id="id_referee_one_social_media_handle" name="referee_one_social_media_handle" type="text" placeholder="Provide link to a social media handle">
                                </div>
                            </div>
                        </div>
                        <strong class="my-4"> Referee 2 </strong>
                        <div class="col-md-6 mb-3">
                            <div>
                                <label for="id_referee_two_full_name">Full Name</label>
                                 <div class="errors-ui">{{ form.referee_two_full_name.errors }}</div>
                                <input class="form-control" id="id_referee_two_full_name" name="referee_two_full_name" type="text" placeholder="Full name">
                            </div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <div>
                                <label for="id_referee_two_email">Email</label>
                                 <div class="errors-ui">{{ form.referee_two_email.errors }}</div>
                                <input class="form-control" id="id_referee_two_email" name="referee_two_email" type="text" placeholder="example@gmail.com">
                            </div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <div>
                                <label for="id_referee_two_phone_number">Phone Number</label>
                                 <div class="errors-ui">{{ form.referee_two_phone_number.errors }}</div>
                                <input class="form-control" id="id_referee_two_phone_number" name="referee_two_phone_number" type="tel" placeholder="+233245000000">
                            </div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <div>
                                <label for="id_referee_two_workplace">Company</label>
                                 <div class="errors-ui">{{ form.referee_two_workplace.errors }}</div>
                                <input class="form-control" id="id_referee_two_workplace" name="referee_two_workplace" type="text" placeholder="Company Ltd.">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-8 mb-3">
                                <div class="form-group">
                                    <label for="id_referee_two_social_media_handle">Link To Social Media Handle</label>
                                     <div class="errors-ui">{{ form.referee_two_social_media_handle.errors }}</div>
                                    <input class="form-control" id="id_referee_two_social_media_handle" name="referee_two_social_media_handle" type="text" placeholder="Provide link to a social media handle">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mt-3">
                        <button type="submit" class="btn btn-primary">Submit Information</button>
                    </div>
                </form>
            </div>
        </div>
                            
    </div>

</main>

{% endblock %}

skn_professionals/templates/choose_request_service.html
{% extends "account/base.html" %}
{% load static %}
{% load i18n %}
{% load account %}

{% block head_title %} Choose Request Service - She Knows Network{% endblock %}


{% block content %}



	<section class="vh-lg-100 d-flex align-items-center">
        <div class="container">
            <!-- <h2 class="justify-content-center"> Choose the type of request service you want</h2> -->
            <div class="row justify-content-center form-bg-image" data-background-lg="">
                
                <div class="col-6 d-flex align-items-center justify-content-center">
                    <div class="signin-inner my-3 my-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                        <div class="text-center text-md-center mb-4 mt-md-0">
                            <h3 class="mb-0 h3">Free Service</h3>
                        </div>
                        
                        <p>Go  through our professional profiles and make contact directly to the professional.</p>

                        <a class="btn btn-sm btn-secondary" href="/find-professionals">Go >></a>

                    </div>
                </div>
                <div class="col-6 d-flex align-items-center justify-content-center">
                    <div class="signin-inner my-3 my-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                        <div class="text-center text-md-center mb-4 mt-md-0">
                            <h1 class="mb-0 h3">Paid Service</h1>
                        </div>
                        
                        <p>We will do the search for you so you get the professional you want.</p>

                        <a class="btn btn-sm btn-secondary" href="">Go >></a>

                    </div>
                </div>
            </div>
        </div>
    </section>


   <!--  <section class="vh-lg-100 d-flex align-items-center">
        <div class="container">
            <div class="row justify-content-center form-bg-image" data-background-lg="">
                <div class="col-12 d-flex align-items-center justify-content-center">
                    <div class="signin-inner my-3 my-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                        <div class="text-center text-md-center mb-4 mt-md-0">
                            <h1 class="mb-0 h3">Paid Service</h1>
                        </div>
                        
                        <p>We will do the search for you so you get the professional you want.</p>

                    </div>
                </div>
            </div>
        </div>
    </section> -->


{% endblock %}

skn_professionals/templates/not_allowed.html
{% extends "account/base.html" %}
{% load static %}
{% load i18n %}
{% load account %}

{% block title %} Verify Account - She Knows Network{% endblock %}


{% block content %}


	<section class="vh-lg-100 d-flex align-items-center">
            <div class="container">
                <div class="row justify-content-center form-bg-image" data-background-lg="">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="signin-inner my-3 my-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">Need Approval</h1>
                            </div>
                            
                            <p>You're not allowed to use this part yet. Kindly talk to support for help on using this part.</p>

                            <!-- <a href="/"> << Go Back </a> -->

                        </div>
                    </div>
                </div>
            </div>
        </section>


{% endblock %}

skn_professionals/templates/recommend_thankyou.html
{% extends "account/base.html" %}
{% load static %}
{% load i18n %}
{% load account %}

{% block head_title %} Thank You - She Knows Network{% endblock %}


{% block content %}


	<section class="vh-lg-100 d-flex align-items-center">
            <div class="container">
            	<div class="row justify-content-center form-bg-image" data-background-lg="">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="signin-inner my-3 my-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                            	<p>Thank you for recommending a professional. We will get in touch with the professional in the shortest possible time. Best Wishes.</p>

                            	<p><a href="/"><< Back to Homepage</a></p>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </section>


{% endblock %}